### ISSUE TITLE
How do I add Procursus Idid to path on Mac?

### ISSUE THREAD

**Issue by TomerGamerTV** [opa334/TrollStore#240]
you didn't explain how to do it

**Comment by CubeBag** [comment]
This may not be the "best way" to do it (since I'm not familiar with Procursus), but it works fine as a quick-and-dirty way and it worked for me:

1. `brew uninstall ldid` (the installation of THEOS installs the wrong ldid)
2. Download it from the repo https://github.com/ProcursusTeam/ldid/releases/tag/v2.1.5-procursus5
3. Rename to `ldid`, do `chmod +x ldid` to make sure you can run it
4. Copy it to `/usr/local/bin`

**Comment by tom-snow** [comment]
If you installed [THEOS](https://theos.dev/docs/installation-macos) before, you don't have to  install it again

If you type ldid into terminal then it find it and run, you'll not need to install `ldid` manually.

**Comment by CubeBag** [comment]
The ldid I installed from brew and the ldid from the Procursus repository had different outputs, and only the Procursus one worked for me


Procursus:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/17459634/194537413-7f5650b6-5d0f-441e-acca-e4f16c4cbfd0.png">

Brew:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/17459634/194537646-4d1d073b-fb90-4883-a916-0968ca8cd21c.png">

**Comment by tom-snow** [comment]
Sorry for my wrong guidance.
