### ISSUE TITLE
When can use trollstore on ios16?

### ISSUE THREAD

**Issue by ghh789** [opa334/TrollStore#367]
Apple has turned off the verification of versions below ios16, so it cannot downgrade the iPhone/iPad below ios16 to conform to the trollstore installation version. This is inconvenient for users above ios15.6, who can only use certificates to sign when installing ipa

**Comment by ghh789** [comment]
用百度翻译翻译的🗡️😊🗡️

**Comment by 3m4r5** [comment]
never

**Comment by ghh789** [comment]
Oh s h i t

**Comment by ShadowRoi** [comment]
Close this issue

**Comment by abcSKY666** [comment]
又是个中国来的

**Comment by teamc00lkidd1** [comment]
patchwerk fat american 胖胖美国人angered hits on armored men对装甲兵的怒吼intentional pain river keeps others safe故意痛苦的河流使他人安全medics focus those who eat fists医务人员将重点放在那些吃拳头的人身上
![7F1BEFA3-CE78-49B6-988A-8C84C6A1A5E9](https://user-images.githubusercontent.com/50070094/208295123-29f3e1b6-13f5-485a-b3a8-7b324042b043.png)
