### ISSUE TITLE
1.01 1.02You can install the ipa directly from iCloud, but 1.03-1.04 can't?

### ISSUE THREAD

**Issue by 95716354** [opa334/TrollStore#46]
1.01 1.02You can install the IPA directly from iCloud, but 1.03-1.04 can't?
1.03-1.04 all need to copy IPA from iCloud to mobile phone to complete the installation. Could you please help to check?

**Comment by WillXProject** [comment]
Already covered, close this issue as this most likely won't be fixed by opa334, it was covered in EDIT 4 on the Reddit thread:
EDIT 4: Small note, TrollStore does not support opening files stored on iCloud drive (installation will silently fail), copy them to your local storage first.
https://www.reddit.com/r/jailbreak/comments/x44cpj/free_release_trollstore_jailed_permasigned_app/
You may verify this information

**Comment by opa334** [comment]
will be fixed shortly

**Comment by opa334** [comment]
should be fixed in 1.0.5
