### ISSUE TITLE
Jailbreak Booting issue

### ISSUE THREAD

**Issue by Cedo9999** [opa334/TrollStore#490]
When I jailbroke for the first time everything went as expected exempt for all my old tweaks(that I installed via fugu15) were gone, I didn't think much of it and I reinstalled them, after respringing via Sileo, my phone crashed, so I jailbroke again. When I did my phone did a user space reboot to finalise the jailbreak,but when it did instead of booting up my phone showed me the Apple logo for an infinite amount of time, not booting up like it always had, effectively giving me a real scare. Please help me

**Comment by admin-elvistrujanovic** [comment]
> When I jailbroke for the first time everything went as expected exempt for all my old tweaks(that I installed via fugu15) were gone, I didn't think much of it and I reinstalled them, after respringing via Sileo, my phone crashed, so I jailbroke again. When I did my phone did a user space reboot to finalise the jailbreak,but when it did instead of booting up my phone showed me the Apple logo for an infinite amount of time, not booting up like it always had, effectively giving me a real scare. Please help me

You can try to boot using ssh ramdisk checkm8 bug (if it's compatible) and if that doesn't allow you to boot not even into unjailbroken state, you soft-bricked your device.


You should (if you can) get some logs and report the bug to the right repository for Fugu15 and after that to clean restore your device using DFU mode and iTunes to the latest signed version or use pwned DFU with saved shsh2 blobs to restore your same iOS version without updating it to the latest version



Just to be sure, don't restore the backup fron iCloud because some broken files from the prevous state can be restored and soft-brick your device again



Good luck!
