### ISSUE TITLE
有一些小细节

### ISSUE THREAD

**Issue by huami1314** [opa334/TrollStore#636]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Fix icon error

### Current Behavior?

After installing the APP, the icon will be displayed on the list of other software. Reopening the trollstore will solve the problem. It is a small detail issue.

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

2.0.8

### iOS/iPadOS version

15.4.1

### iDevice Model

iPhone 13 Pro

### Other info of your environment

-

**Comment by huami1314** [comment]
![Uploading 3B39644F-B505-48D2-8A63-DFC64908FCEC.png…]()

**Comment by huami1314** [comment]
![B5AA8D8B-9FEE-4C8A-9791-7A0AFBD46153](https://github.com/opa334/TrollStore/assets/99124359/689aa25e-328e-4023-bae6-b81a17c1e689)

**Comment by huami1314** [comment]
![Uploading 54223BD5-FE51-480E-879F-EFB7AF908722.png…]()

**Comment by huami1314** [comment]
![9C050115-4A7C-4650-8972-66B62B1CD685](https://github.com/opa334/TrollStore/assets/99124359/c79dd32b-3d36-4c7a-bfa3-166242da09dc)

**Comment by huami1314** [comment]
![3889A477-2CAF-44A0-826D-0FB62F7E4124](https://github.com/opa334/TrollStore/assets/99124359/4392da64-b39b-46c1-ba02-4baf561942ea)

**Comment by sowavy234** [comment]
Im on iPhone, 14 Pro Max iOS 17.2 with the latest altBurberry.On Nov 30, 2023, at 6:35 PM, huami. ***@***.***> wrote:﻿
No Duplicates Issue

 I'm sure I've searched on the issue tracker before creating one.

Expected Behavior?
Fix icon error
Current Behavior?
After installing the APP, the icon will be displayed on the list of other software. Reopening the trollstore will solve the problem. It is a small detail issue.
Possible Solution?



Steps to Reproduce



TrollStore Version
2.0.8
iOS/iPadOS version
15.4.1
iDevice Model
iPhone 13 Pro
Other info of your environment

**Comment by sowavy234** [comment]
What’s that Burberry.On Nov 30, 2023, at 6:35 PM, huami. ***@***.***> wrote:﻿
