### ISSUE TITLE
Battery drainage?

### ISSUE THREAD

**Issue by Gelby** [opa334/TrollStore#674]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

Battery should only drain a couple percent every few hours

### Current Behavior?

Battery has been draining while idle/locked like crazy. Last night I tested to see how bad it was, it went from 85% to dead while I was sleeping (roughly 8 hours)... I can't be ABSOLUTELY certain it's Trollstore's fault but it's been draining a lot since I installed Trollstore

### Steps to Reproduce

Just use Trollstore

### TrollStore Version

Trollstore 2.0.8

### iOS/iPadOS version

16.4

### iDevice Model

iPhone 14 pro

**Comment by opa334** [comment]
TrollStore cannot cause battery drain

**Comment by MrCream-22** [comment]
He is right i have my iphone 14 pro since June 2023 and it was at 100% battery condition, since I installed trollstore 2 weeks ago my phone is down to 97%, my iPhone 11 pro was doing the same with troll store v1 it went from 100% to 83%.

I was wondering if trollstore was the problem, or maybe it's the ipa applications installed in it that are the problem

**Comment by opa334** [comment]
No, even IPAs you install don't have an effect on this
