### ISSUE TITLE
Huge issue with code.

### ISSUE THREAD

**Issue by TheOneWhoIsCool** [opa334/TrollStore#688]
The issue is everyone is getting Error Code 180 & 175. This isn’t very stable, but people can downgrade to 2.0.8 to fix this issue. Although, please don’t just delete 2.0.9. It adds developer mode, helpful to many users.

**Comment by phong010198** [comment]
I faced this 180 too.
Decrypt using TrollDecrypt -> inject deb using Azule -> 2.0.9 show error 180, while 2.0.8 can install app perfectly.

**Comment by Sukixo** [comment]
Getting 175 error on latest TrollStore

“Failed to sign app. Idid returned a non zero status code.”

**Comment by alfiecg24** [comment]
Error 180 comes from trying to install an app with an encrypted binary. While you may think that your IPA is decrypted, app extensions and plugins are often left encrypted. Perhaps the way to get around this is to only bail out if the main binary is encrypted. However, there will be broken functionality if the app extensions are not decrypted.

Error 175 is more of a general error. In your original issue, you tried PojavLauncher and it failed. This was caused by one of the binaries seemingly not having the fallback entitlements applied to it (as it ships without any entitlements). It's being looked into at the moment.

**Comment by foxfortmobile** [comment]
> Error 180 comes from trying to install an app with an encrypted binary. While you may think that your IPA is decrypted, app extensions and plugins are often left encrypted. Perhaps the way to get around this is to only bail out if the main binary is encrypted, and instead display a warning if the extensions are encrypted. However, there will be broken functionality if the app extensions are not decrypted.
> 
> Error 175 is more of a general error. In your original issue, you tried PojavLauncher and it failed. This was caused by one of the binaries seemingly not having the fallback entitlements applied to it (as it ships without any entitlements). It's being looked into at the moment.

I am getting the error 80 with 7 different versions of a decrypted ipa of the same app. While i understand the cause of the issue, i believe this will make Trollstore more limited. For example i can install the ipa which still contains 1 encrypted plugin using any installer tool like xcode/itunes/sideloadly but the same ipa completely fails to install using Trollstore. 

Furthermore is no tool that can properly decrypt all binaries inside an ipa. i have tried appdecrypt, dumpdecrypter, iridium, appsdump, flexdecrypt, trolldecryptor on a tiktok ipa & a few plugins failed to decrypt. I even downloadeded other versions of the ipa from websites and they all fail. At this point, this feels like a complete blocking point. I believe plenty of others who have existing ipas from somewhere will run into this and they will only try to find a way to downgrade to older TrollStore version to install it. It is unlikely that they will figure out a way to get completely decrypted versions of those apps since i tried with 7 tools and completely failed.

It would be better if the check is removed competely or only applied to the main binary because for majority of apps, it does not matter if a plugin fails to load. Plugins are generally optional and separated from main app binary and if they fail to load, most of the time it's not an issue for the user since he can still fully use the app.

**Comment by yur1xpp** [comment]
> > Error 180 comes from trying to install an app with an encrypted binary. While you may think that your IPA is decrypted, app extensions and plugins are often left encrypted. Perhaps the way to get around this is to only bail out if the main binary is encrypted, and instead display a warning if the extensions are encrypted. However, there will be broken functionality if the app extensions are not decrypted.
> > Error 175 is more of a general error. In your original issue, you tried PojavLauncher and it failed. This was caused by one of the binaries seemingly not having the fallback entitlements applied to it (as it ships without any entitlements). It's being looked into at the moment.
> 
> I am getting the error 180 with 7 different versions of a decrypted ipa of the same app. While i understand the cause of the issue, i believe this will make Trollstore more limited. For example i can install the ipa which still contains 1 encrypted plugin using any installer tool like xcode/itunes/sideloadly but the same ipa completely fails to install using Trollstore.
> 
> Furthermore is no tool that can properly decrypt all binaries inside an ipa. i have tried appdecrypt, dumpdecrypter, iridium, appsdump, flexdecrypt, trolldecryptor on a tiktok ipa & a few plugins failed to decrypt. I even downloadeded other versions of the ipa from websites and they all fail. At this point, this feels like a complete blocking point. I believe plenty of others who have existing ipas from somewhere will run into this and they will only try to find a way to downgrade to older TrollStore version to install it. It is unlikely that they will figure out a way to get completely decrypted versions of those apps since i tried with 7 tools and completely failed.
> 
> It would be better if the check is removed competely or only applied to the main binary because for majority of apps, it does not matter if a plugin fails to load. Plugins are generally optional and separated from main app binary and if they fail to load, most of the time it's not an issue for the user since he can still fully use the app.

If you don't mind cli tool, [Azule](https://github.com/Al4ise/Azule) did completely decrypted all the binaries, I haven't have any issue with all the apps I've decrypted with.

While I agree that TS should allow the installation when there's encrypted binaries, but I hope a warning will popup or ask for user confirmation to proceed with the installation. The reason is that encrypted binary should be treated as "corrupted" IPA since ideally this broke the functionality of the app in some way. By that, user will unknowingly installed a problematic IPA through TS compared to from App Store, and that leave them blaming TS.

**Comment by alfiecg24** [comment]
This has been fixed and will come in a TrollStore release soon.

**Comment by wokedos** [comment]
update out
