### ISSUE TITLE
unsupported button thingy :(

### ISSUE THREAD

**Issue by moegirlspit** [opa334/TrollStore#847]
### No Duplicates Issue

- [X] I'm sure I've searched on the issue tracker before creating one.

### Expected Behavior?

i think i was supposed to open the trollinstaller, change some settings if necessary, and then click the 'install' button to. install it

### Current Behavior?

instead, the install button is replaced with an 'unsupported' thingy that i can't click on, and the settings and credits are also unclickable. very dilemma-ic i know

### Possible Solution?

-

### Steps to Reproduce

-

### TrollStore Version

TrollInstallerX

### iOS/iPadOS version

iPadOS 15.8.3

### iDevice Model

iPad Air 2

**Comment by scetayh** [comment]
Probably your device or os version isn’t support? I’ve noticed I have the same dev/os as yours, which is air 2/15.8.3


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: moegirlspit ***@***.***>
发送时间: Saturday, October 26, 2024 2:56:06 AM
收件人: opa334/TrollStore ***@***.***>
抄送: Subscribed ***@***.***>
主题: [opa334/TrollStore] unsupported button thingy :( (Issue #847)


No Duplicates Issue

  *    I'm sure I've searched on the issue tracker before creating one.

Expected Behavior?

i think i was supposed to open the trollinstaller, change some settings if necessary, and then click the 'install' button to. install it

Current Behavior?

instead, the install button is replaced with an 'unsupported' thingy that i can't click on, and the settings and credits are also unclickable. very dilemma-ic i know

Possible Solution?

  *

Steps to Reproduce

  *

TrollStore Version

TrollInstallerX

iOS/iPadOS version

iPadOS 15.8.3

iDevice Model

iPad Air 2

Other info of your environment

No response

―

**Comment by alfiecg24** [comment]
Please follow [this guide](https://ios.cfw.guide/installing-trollstore-trollmisaka).
