### ISSUE TITLE
Kodi not working

### ISSUE THREAD

**Issue by N3XuS-eXe** [opa334/TrollStore#92]
Kodi not working

**Comment by djabif-gh** [comment]
More precisely, Kodi version 19.4 gives "Install Error 173". With Kodi version 18.x installs, but the Kodi do not work, black screen appears.
Using AltServer or Sideloadly works fine both versions.

**Comment by opa334** [comment]
Issue with Kodi IPA, some framework inside it is weird and ldid does not like it

**Comment by justinkb** [comment]
this is caused by the .app including a Mach-O object file, specifically ./Frameworks/lib/python3.11/config-3.11-darwin/python.o, which ldid chokes on, since it's neither an executable, a dylib or a bundle. Removing that config-3.11-darwin folder fixes the issue, doesn't seem like it should be included anyway, unless I'm mistaken it's only used to compile something against that python library on the platform, which isn't a sane use case for the embedded python library for Kodi.
